import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg-void": "#05070D",
        "surface": "#0f131d",
        "surface-dim": "#0f131d",
        "surface-bright": "#353944",
        "surface-panel": "#0C101A",
        "surface-elevated": "#141A28",
        "surface-overlay": "#080E1C",
        "surface-container-lowest": "#0a0e18",
        "surface-container-low": "#171b26",
        "surface-container": "#1b1f2a",
        "surface-container-high": "#262a35",
        "surface-container-highest": "#313540",
        "surface-variant": "#313540",
        "on-surface": "#dfe2f1",
        "on-surface-variant": "#b9cacb",
        "inverse-surface": "#dfe2f1",
        "inverse-on-surface": "#2c303b",
        "outline": "#849495",
        "outline-variant": "#3b494b",
        "surface-tint": "#00dbe9",
        "primary": "#dbfcff",
        "on-primary": "#00363a",
        "primary-container": "#00f0ff",
        "on-primary-container": "#006970",
        "primary-fixed": "#7df4ff",
        "primary-fixed-dim": "#00dbe9",
        "secondary": "#ddb7ff",
        "on-secondary": "#490080",
        "secondary-container": "#6f00be",
        "on-secondary-container": "#d6a9ff",
        "secondary-fixed": "#f0dbff",
        "secondary-fixed-dim": "#ddb7ff",
        "tertiary": "#daffe4",
        "on-tertiary": "#003920",
        "tertiary-container": "#00f89e",
        "on-tertiary-container": "#006d43",
        "tertiary-fixed": "#52ffac",
        "tertiary-fixed-dim": "#00e290",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "warning": "#ffb800",
        "cyber-cyan": "#00F0FF",
        "cyber-violet": "#A855F7",
        "cyber-emerald": "#00FFA3",
        "cyber-red": "#FF3366",
        "cyber-amber": "#FFB800",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1rem",
        "gutter-lg": "1.5rem",
        "margin": "1rem",
        "margin-md": "1.5rem",
        "margin-lg": "2.5rem",
      },
      fontFamily: {
        "display-hero": ["'Space Grotesk'", "sans-serif"],
        "headline-lg": ["'Space Grotesk'", "sans-serif"],
        "headline-md": ["'Space Grotesk'", "sans-serif"],
        "body-lg": ["'Geist'", "'Inter'", "sans-serif"],
        "body-md": ["'Geist'", "'Inter'", "sans-serif"],
        "body-sm": ["'Geist'", "'Inter'", "sans-serif"],
        "code-md": ["'JetBrains Mono'", "monospace"],
        "label-mono": ["'JetBrains Mono'", "monospace"],
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "spin-slow": "spin 20s linear infinite",
        "float": "float 6s ease-in-out infinite",
        "glow": "glow 2s ease-in-out infinite alternate",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        glow: {
          "0%": { boxShadow: "0 0 10px rgba(0, 240, 255, 0.2)" },
          "100%": { boxShadow: "0 0 25px rgba(0, 240, 255, 0.6)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
